spring:
  datasource:
    url: jdbc:mysql://localhost:3320/moviedb?useSSL=false&allowPublicKeyRetrieval=true
    username: movieadmin
    password: movie
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create